version: 5.4.2

service:
  sparkle-patch:
    image: quay.io/fedora/nodejs-24
    container_name: build_sparkle_patch

  volumes:
    - ./sparkle:/_project/sparkle:ro
    - ./temp/patch/electron-builder.ymal:/_project/sparkle/electron-builder.yml:ro
    - ./export:/_project/sparkle/export:rw

  tmpfs:
    - /_project/sparkle/dist
